analytics.integration.enable=true
analytics.onpremise.enable=false
analytics.project={"id"\:3461456,"name"\:"pruebas-equipo5-AutomationExercise","teamId"\:3443409,"status"\:null,"gitRepositories"\:null,"team"\:null,"organizationId"\:3486734,"accountId"\:null,"autoIntegrate"\:false,"sampleProject"\:false}
analytics.team={"id"\:3443409,"role"\:null,"name"\:null,"organization"\:null}
analytics.testcloud.integration.enable=true
analytics.testreport.autoupload.enable=true
